# Generated by Django 5.0.6 on 2024-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('published_year', models.IntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('genre', models.CharField(choices=[('dr', 'Drama'), ('rm', 'Romance'), ('my', 'Mystery'), ('hr', 'Horror'), ('hs', 'Histery'), ('sc', 'Science')], max_length=2, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
